INSERT INTO `musicplayer` (`song`, `album`, `interpret`, `url`) VALUES
('IGNITE', 'Sword Art Online II OP Single IGNITE', 'Aoi Eir', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/2.mp3'),
('crossing field', 'Sword Art Online OP Single crossing field', 'LiSA', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/3.mp3'),
('Luminous Swords', 'Sword Art Online OST', 'LiSA', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/19%20-%20luminous%20sword.mp3'),
('Cantina Band', 'Star Wars OST', 'John Williams', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/cantina.mp3'),
('Metal Gear Solid Main Theme', 'Metal Gear Solid Snake Eater OST', '', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/01-metal-gear-solid-main-theme.mp3'),
('Promise (Reprise)', 'Silent Hill 2 OST', '', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/Promise%20(Reprise).mp3'),
('Betrayal', 'Silent Hill 2 OST', '', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/Betrayal.mp3'),
('Accidentally in Love', 'Shrek 2 OST', 'Counting Crows', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/Counting%20Crows%20-%20Accidentally%20in%20Love.mp3'),
('Rachnera Arachnera', 'Monster Musume Iru no nichijou Character Soundtrack Rachnera Arachnera', 'Sakura Nakamura', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/01.%20Rachnera%20Arachnera.mp3'),
('PAPISM', 'Monster Musume Iru no nichijou Character Soundtrack Papi the Harpy', 'Ari Ozawa', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/01%20PAPISM.mp3'),
('Amagasa no Uta', 'Monster Musume Iru no nichijou Character Soundtrack Suu', 'Mayuka Nomura', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/01%20Amagasa%20no%20Uta.mp3'),
('Saikousoku Fall in Love', 'Monster Musume Iru no nichijou OST', 'Sora Amamiya, Ari Ozawa, etc', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/Monster%20Musume%20No%20Iru%20Nichijou%20Saikousoku%20Fall%20In%20Love%20_%20%5bOP%20Full%5d%20(mp3searched.net).mp3'),
('Hey! Smith!', 'Monster Musume Iru no nichijou OST', 'Sumisu and MON', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/Sumisu%20and%20MON-Hey!%20Smith!!%20www.123savemp3.net%20.mp3'),
('Yami no Condact', '', 'Phrenia', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/Phrenia_-_Yami_no_Condact.mp3'),
('SIGNAL', '', 'Phrenia', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/Phrenia_-_SIGNAL.mp3'),
('%u521D%u604B', 'nj(%u30A8%u30CC%u30B8%u30A7%u30A4) - n.j. from GBU', 'MenT@i', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/1.mp3'),
('Ass n Titties', '', 'DJ Assault', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/DJ%20Assault%20-%20Ass-n-titties.mp3'),
('Dont stop me now', '', 'Queen', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/tumblr_mjit5lJ0c81re6h6zo1.mp3'),
('MeMeMe', 'google it!', '', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/MeMeMe.mp3'),
('Guren no yumiya', 'Attack on Titan OST', 'Linked Horizon', 'https://raw.githubusercontent.com/Linkyoshi90/Asperger_forum/master/music/josha/Linked%20horizon%20guren%20no%20yumiya.mp3');